[package]
name = "audros-client"
version = "0.1.0"
authors = ["marcelbuesing <marcel.buesing@daimler.com>"]
build = "build.rs"

[build-dependencies]
protoc-grpcio = "0.1.0"

[dependencies]
futures = "0.1.18"
futures-await = "0.1.0"
grpcio = "0.2.1"
protobuf = "1.4.4"
